# Generated by Django 5.2.6 on 2025-09-19 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200, null=True)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "override_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("phone_number", "Phone_number"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("phone_number", "Phone_number"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Строка контакта переданная пользователем",
                        max_length=128,
                    ),
                ),
                (
                    "normalized_value",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Строка контакта после приведения к стандарту",
                        max_length=128,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Активен ли канал(для сервиса рассылки)"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Подтверждение контакта пользователем"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["contact_type", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "contact_type"), name="uniq_user_contact_type"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_verified", True)),
                        fields=("contact_type", "normalized_value"),
                        name="uniq_verified_contact_value",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_notification_channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("phone_number", "Phone_number"),
                        ],
                        default="email",
                        max_length=24,
                    ),
                ),
                ("notification_consent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "настройка уведомления",
                "verbose_name_plural": "Настройки уведомлений",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "preferred_notification_channel__in",
                                ["email", "telegram", "phone_number"],
                            )
                        ),
                        name="valid_channel",
                    )
                ],
            },
        ),
    ]
