# Generated by Django 5.2.6 on 2025-09-18 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_notification_channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("phone_number", "Phone_number"),
                        ],
                        default="email",
                        max_length=24,
                    ),
                ),
                ("notification_consent", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "настройка уведомления",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
        migrations.CreateModel(
            name="UserContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("phone_number", "Phone_number"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Строка контакта переданная пользователем",
                        max_length=128,
                    ),
                ),
                (
                    "normalized_value",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Строка контакта после приведения к стандарту",
                        max_length=128,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Активен ли канал(для сервиса рассылки)"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Подтверждение контакта пользователем"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["contact_type", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "contact_type"), name="uniq_user_contact_type"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_verified", True)),
                        fields=("contact_type", "normalized_value"),
                        name="uniq_verified_contact_value",
                    ),
                ],
            },
        ),
    ]
